name       : haskell-store
version    : 0.3.1
release    : 1
source     :
    - http://hackage.haskell.org/package/store-0.3.1/store-0.3.1.tar.gz : ec1005ebaf7334f6e5166315f8406553c94cffa8e06bc1d60f372c0d46ceda90
license    : MIT
component  : programming.haskell
summary    : The 'store' package provides efficient binary serialization.
description: |
    The 'store' package provides efficient binary serialization.
builddeps  :
    - haskell-cabal-install
    - haskell-conduit
    - haskell-cryptohash
    - haskell-fail
    - haskell-free
    - haskell-hspec
    - haskell-hspec-smallcheck
    - haskell-mono-traversable
    - haskell-store-core
    - haskell-streaming-commons
    - haskell-th-utilities
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
