name       : haskell-store
version    : 0.4.3.2
release    : 2
source     :
    - http://hackage.haskell.org/package/store-0.4.3.2/store-0.4.3.2.tar.gz : eca47c14b14ce5a6369a4b09a048b5a7fe7574d3f1b1099bc03449416c80308e
license    : MIT
component  : programming.haskell
summary    : The 'store' package provides efficient binary serialization.
description: |
    The 'store' package provides efficient binary serialization.
builddeps  :
    - haskell-base64-bytestring
    - haskell-cabal-install
    - haskell-conduit
    - haskell-cryptohash
    - haskell-fail
    - haskell-free
    - haskell-hspec
    - haskell-hspec-smallcheck
    - haskell-lifted-base
    - haskell-monad-control
    - haskell-mono-traversable
    - haskell-store-core
    - haskell-streaming-commons
    - haskell-th-utilities
    - haskell-void
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
