name       : haskell-store
version    : 0.7.8
release    : 4
source     :
    - https://hackage.haskell.org/package/store-0.7.8/store-0.7.8.tar.gz : e3c716913e5d60920a73dc752b6de6aee5563e5bbb5085effc157cfe4016617c
license    : MIT
component  : programming.haskell
summary    : The 'store' package provides efficient binary serialization.
description: |
    The 'store' package provides efficient binary serialization.
builddeps  :
    - haskell-async-devel
    - haskell-base64-bytestring-devel
    - haskell-cabal-install
    - haskell-cryptohash-devel
    - haskell-free-devel
    - haskell-hspec-devel
    - haskell-hspec-smallcheck-devel
    - haskell-lifted-base-devel
    - haskell-mono-traversable-devel
    - haskell-network-devel
    - haskell-resourcet-devel
    - haskell-store-core-devel
    - haskell-th-utilities-devel
rundeps    :
    - devel:
        - haskell-async-devel
        - haskell-base64-bytestring-devel
        - haskell-cryptohash-devel
        - haskell-free-devel
        - haskell-hspec-devel
        - haskell-hspec-smallcheck-devel
        - haskell-lifted-base-devel
        - haskell-mono-traversable-devel
        - haskell-network-devel
        - haskell-resourcet-devel
        - haskell-store-core-devel
        - haskell-th-utilities-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
